project:
  type: book
  output-dir: docs

book:
  title: "Desarrollo e Implementación con tecnologías libres de un Dispositivo Portátil para Evaluar el Confort Térmico, Lumínico y Acústico en Interiores"
  author: "José Ramón Hernández Aguilar"
  date: "12/25/2024"
  chapters:
    - index.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - references.qmd
    - anexos.qmd

  navbar:
    title: false
    search: true

  sidebar:
    style: floating
    search: true
    collapse-level: 1

format:
  html:
    toc: true
    toc-title: Contenido
    toc-depth: 4
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-link: true
  pdf:
    documentclass: scrreprt

bibliography: references.bib