<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Calibración y referenciación del DTHIS-C – Desarrollo e implementación con tecnologías libres de un dispositivo portátil para evaluar el confort térmico, lumínico y acústico en interiores</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter_5.html" rel="next">
<link href="./chapter_3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Buscar"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_4.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Calibración y referenciación del DTHIS-C</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción al confort en espacios interiores y el desarrollo del DTHIS-C</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Confort y calidad del aire en espacios interiores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Diseño y construcción del DTHIS-C</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_4.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Calibración y referenciación del DTHIS-C</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusiones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografía</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anexos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anexos</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#sec-metodologia" id="toc-sec-metodologia" class="nav-link active" data-scroll-target="#sec-metodologia"><span class="header-section-number">4.1</span> Metodología experimental</a></li>
  <li><a href="#sec-obtencion" id="toc-sec-obtencion" class="nav-link" data-scroll-target="#sec-obtencion"><span class="header-section-number">4.2</span> Obtención y visualización de los datos</a>
  <ul>
  <li><a href="#thingsboard" id="toc-thingsboard" class="nav-link" data-scroll-target="#thingsboard">ThingsBoard</a></li>
  <li><a href="#temperatura-ambiente" id="toc-temperatura-ambiente" class="nav-link" data-scroll-target="#temperatura-ambiente">Temperatura ambiente</a></li>
  <li><a href="#temperatura-radiante" id="toc-temperatura-radiante" class="nav-link" data-scroll-target="#temperatura-radiante">Temperatura radiante</a></li>
  <li><a href="#velocidad-del-viento" id="toc-velocidad-del-viento" class="nav-link" data-scroll-target="#velocidad-del-viento">Velocidad del viento</a></li>
  <li><a href="#humedad-relativa-y-co2" id="toc-humedad-relativa-y-co2" class="nav-link" data-scroll-target="#humedad-relativa-y-co2">Humedad relativa y CO<sub>2</sub></a></li>
  <li><a href="#sonido" id="toc-sonido" class="nav-link" data-scroll-target="#sonido">Sonido</a></li>
  <li><a href="#iluminancia" id="toc-iluminancia" class="nav-link" data-scroll-target="#iluminancia">Iluminancia</a></li>
  </ul></li>
  <li><a href="#sec-analisis" id="toc-sec-analisis" class="nav-link" data-scroll-target="#sec-analisis"><span class="header-section-number">4.3</span> Análisis e interpretación de resultados</a>
  <ul>
  <li><a href="#temperatura-ambiente-1" id="toc-temperatura-ambiente-1" class="nav-link" data-scroll-target="#temperatura-ambiente-1">Temperatura ambiente</a></li>
  <li><a href="#temperatura-radiante-1" id="toc-temperatura-radiante-1" class="nav-link" data-scroll-target="#temperatura-radiante-1">Temperatura radiante</a></li>
  <li><a href="#velocidad-del-viento-1" id="toc-velocidad-del-viento-1" class="nav-link" data-scroll-target="#velocidad-del-viento-1">Velocidad del viento</a></li>
  <li><a href="#humedad-relativa-y-co2-1" id="toc-humedad-relativa-y-co2-1" class="nav-link" data-scroll-target="#humedad-relativa-y-co2-1">Humedad relativa y CO<sub>2</sub></a></li>
  <li><a href="#sonido-1" id="toc-sonido-1" class="nav-link" data-scroll-target="#sonido-1">Sonido</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="cap-calibracion" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Calibración y referenciación del DTHIS-C</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>En este capítulo se detalla el proceso de calibración y referenciación del DTHIS-C. Se describen las metodologías experimentales empleadas para validar su precisión, así como las pruebas realizadas en diferentes escenarios. Además, se presentan y analizan los resultados obtenidos en términos de variables térmicas, lumínicas y acústicas, ofreciendo una evaluación integral de su desempeño. Finalmente, se explican las herramientas y procedimientos para la recuperación, visualización e interpretación de los datos recopilados.</p>
<section id="sec-metodologia" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-metodologia"><span class="header-section-number">4.1</span> Metodología experimental</h2>
<p>Dado que cada sensor mide diferentes variables físicas y sus mediciones se obtienen de manera distinta, se han diseñado campañas de calibración y referenciación adaptadas a las características propias de cada instrumento. Este proceso responde a la necesidad de garantizar la exactitud, confiabilidad y trazabilidad de los datos recopilados.</p>
<p>La metodología experimental se basa en obtener mediciones precisas que permitan validar el desempeño del dispositivo en condiciones reales. Para ello, se definieron procedimientos apoyados en instrumentos de referencia certificados, lo que facilita la detección y corrección de desviaciones inherentes a cada sensor, asegurando resultados consistentes tanto en condiciones controladas como en situaciones de campo.</p>
<p>La aplicación de estos procedimientos refuerza la integridad de la adquisición de datos y favorece una optimización continua del sistema, facilitando su integración en diversos contextos de aplicación.</p>
<p>A continuación se muestra en la <a href="#tbl-instrumentos" class="quarto-xref">Tabla&nbsp;<span>4.1</span></a> la lista de los sensores y sus respectivos instrumentos de referencia utilizados para la calibración y referenciación:</p>
<div id="tbl-instrumentos" class="hover sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-instrumentos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.1: Instrumentos de calibración y referenciación para los sensores que consitutyen al DTHIS-C.
</figcaption>
<div aria-describedby="tbl-instrumentos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-hover table-sm small caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 24%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable</strong></th>
<th><strong>Sensor</strong></th>
<th><strong>Instrumento</strong></th>
<th><strong>Procedimiento</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Temperatura ambiente</td>
<td>Termopar tipo T</td>
<td>AMETEK Jofra PTC-155</td>
<td>Calibración</td>
</tr>
<tr class="even">
<td>Temperatura radiante</td>
<td>TPF1/E-20 PT1000</td>
<td>Quest Technologies QUESTemp 36</td>
<td>Calibración</td>
</tr>
<tr class="odd">
<td>Velocidad del viento</td>
<td>Wind Sensor Rev P6</td>
<td>Gill Instruments WindMaster</td>
<td>Calibración</td>
</tr>
<tr class="even">
<td>CO<sub>2</sub> y humedad relativa</td>
<td>SCD30 Sensirion</td>
<td>Fluke 975 AirMeter</td>
<td>Referenciación</td>
</tr>
<tr class="odd">
<td>Sonido</td>
<td>Micrófono ambiental USB</td>
<td>TES-1356 Sound Level Calibrator</td>
<td>Calibración</td>
</tr>
<tr class="even">
<td>Luminancia</td>
<td>5MP OV5647 Wide Angle Fisheye Camera</td>
<td>No aplica</td>
<td>No aplica</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-obtencion" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-obtencion"><span class="header-section-number">4.2</span> Obtención y visualización de los datos</h2>
<section id="thingsboard" class="level4">
<h4 class="anchored" data-anchor-id="thingsboard">ThingsBoard</h4>
<p>ThingsBoard es una plataforma IoT de código abierto diseñada para la recopilación, procesamiento, visualización y gestión de dispositivos, <span class="citation" data-cites="thingsboard">ThingsBoard (<a href="references.html#ref-thingsboard" role="doc-biblioref">2023</a>)</span>. En el contexto de esta tesis, se utiliza para transmitir en tiempo real las mediciones obtenidas de los distintos sensores del DTHIS-C hacia un servidor central, donde se alojan y resguardan los datos en una base de datos dedicada a Internet de las Cosas.</p>
<p>Según la documentación oficial de ThingsBoard, la plataforma admite la conectividad mediante protocolos estándares como MQTT, CoAP y HTTP, lo que facilita la integración de diversos dispositivos y sensores, <span class="citation" data-cites="thingsboard">ThingsBoard (<a href="references.html#ref-thingsboard" role="doc-biblioref">2023</a>)</span>. En este caso, las mediciones de los sensores se envían desde el DTHIS-C a ThingsBoard, que actúa como un repositorio seguro y escalable. La plataforma no solo almacena la información, sino que también permite la creación de dashboards interactivos y personalizables que posibilitan la visualización en tiempo real de las mediciones. Esto es fundamental durante las campañas de medición, ya que permite monitorizar de forma inmediata el desempeño de los sensores, identificar tendencias y detectar posibles anomalías en los datos.</p>
<p>Para obtener datos directamente desde ThingsBoard, se desarrolló una función en el paquete instalable de Python denominado <code>iertools</code>, creado por el Grupo de Energía en Edificaciones. Este paquete se puede instalar desde la consola de su ordenador (previamente contando con una distribución de Python instalada) mediante el siguiente comando:</p>
<div id="02c626bf" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pip install git<span class="op">+</span>https:<span class="op">//</span>github.com<span class="op">/</span>AltamarMx<span class="op">/</span>iertools.git</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Es importante señalar que, antes de proceder a la obtención y descarga de datos desde ThingsBoard, es necesario crear un archivo de configuración con extensión <code>.ini</code>. Un archivo .ini es un documento de texto plano que almacena parámetros y opciones en formato clave-valor, y se utiliza para definir la configuración necesaria (como la URL del servidor y el token de acceso) que el paquete <code>iertools</code> requiere para conectarse a ThingsBoard.</p>
<p>A continuación, se presenta un ejemplo de cómo estructurar dicho archivo:</p>
<div id="5bbd3637" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>[dthisc]</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>token     <span class="op">=</span> token</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>device_id <span class="op">=</span> device_id</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>tenant    <span class="op">=</span> lata_testing<span class="op">@</span>ier.unam.mx</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>password  <span class="op">=</span> password</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>host      <span class="op">=</span> tb.ier.unam.mx</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>port      <span class="op">=</span> <span class="dv">8080</span> </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Una vez instalado <code>iertools</code>, es posible recuperar datos desde un script o notebook. El siguiente fragmento de código ilustra cómo obtener los datos de medición de los termopares del DTHIS-C a partir de ThingsBoard; este ejemplo puede ser ajustado según las necesidades específicas, permitiendo extraer distintos conjuntos de datos o modificar parámetros conforme a los requerimientos del estudio:</p>
<div id="76e89aef" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-overflow-wrap code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> iertools.tb <span class="im">import</span> <span class="op">*</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>fecha1 <span class="op">=</span> parse(<span class="st">"2024-11-22"</span>) </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>fecha2 <span class="op">=</span> fecha1 <span class="op">+</span> pd.Timedelta(<span class="st">"1D"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>tmp <span class="op">=</span> TB(config_file<span class="op">=</span><span class="st">'data/config.ini'</span>, device_name<span class="op">=</span><span class="st">'dthisc'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>sensores <span class="op">=</span> [<span class="st">"TEMP1"</span>, <span class="st">"TEMP2"</span>, <span class="st">"TEMP3"</span>, <span class="st">"TEMP4"</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.concat([tmp.get_df(key<span class="op">=</span>sensor,start_datetime<span class="op">=</span>fecha1,end_datetime<span class="op">=</span>fecha2) <span class="cf">for</span> sensor <span class="kw">in</span> sensores],axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>hora_inicio <span class="op">=</span> <span class="st">"2024-11-22 15:42"</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>hora_fin <span class="op">=</span> <span class="st">"2024-11-22 17:09"</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data[(data.index <span class="op">&gt;=</span> hora_inicio) <span class="op">&amp;</span> (data.index <span class="op">&lt;=</span> hora_fin)]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>data.sort_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>data.head(<span class="dv">10</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TEMP1</th>
<th data-quarto-table-cell-role="th">TEMP2</th>
<th data-quarto-table-cell-role="th">TEMP3</th>
<th data-quarto-table-cell-role="th">TEMP4</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">ts</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:00.774</td>
<td>12.42</td>
<td>12.63</td>
<td>13.81</td>
<td>13.48</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:03.505</td>
<td>12.37</td>
<td>12.57</td>
<td>13.81</td>
<td>13.46</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:06.235</td>
<td>12.44</td>
<td>12.61</td>
<td>13.75</td>
<td>13.48</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:08.965</td>
<td>12.46</td>
<td>12.59</td>
<td>13.79</td>
<td>13.45</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:11.697</td>
<td>12.38</td>
<td>12.51</td>
<td>13.75</td>
<td>13.44</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:14.427</td>
<td>12.35</td>
<td>12.56</td>
<td>13.77</td>
<td>13.41</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:17.159</td>
<td>12.41</td>
<td>12.63</td>
<td>13.73</td>
<td>13.40</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:19.892</td>
<td>12.41</td>
<td>12.52</td>
<td>13.66</td>
<td>13.38</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:22.620</td>
<td>12.38</td>
<td>12.56</td>
<td>13.66</td>
<td>13.40</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2024-11-22 15:42:25.351</td>
<td>12.34</td>
<td>12.52</td>
<td>13.72</td>
<td>13.34</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Finalmente, para almacenar los datos recuperados, se puede utilizar el siguiente comando para exportarlos a un archivo CSV:</p>
<div id="cd658b8a" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data.to_csv(<span class="st">"ruta/de/su/preferencia.csv"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="temperatura-ambiente" class="level4">
<h4 class="anchored" data-anchor-id="temperatura-ambiente">Temperatura ambiente</h4>
<p>En esta campaña de calibración se utilizó el AMETEK Jofra PTC-155 (<a href="#fig-AMETEK" class="quarto-xref">Figura&nbsp;<span>4.1</span></a>), un calibrador de temperatura que permite evaluar sensores en un rango de -25°C a 155°C.</p>
<div id="fig-AMETEK" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-AMETEK-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\images/ametek.jpg" class="img-fluid figure-img" style="width:25.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-AMETEK-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: AMETEK Jofra PTC-155.
</figcaption>
</figure>
</div>
<p>El instrumento mencionado se utilizó junto a cuatro termopares tipo T, estableciendo cinco puntos de referencia de temperatura en el intervalo de 10°C a 50°C.</p>
<p>Para cada punto de calibración, se esperó aproximadamente 5 minutos para que el calibrador alcanzara y estabilizara la temperatura deseada. Una vez estabilizada, se registraron los datos durante 10 minutos antes de proceder al siguiente punto. Los resultados obtenidos en esta campaña se pueden observar en la <a href="#fig-termopares" class="quarto-xref">Figura&nbsp;<span>4.2</span></a>.</p>
<div id="cell-fig-termopares" class="cell" data-execution_count="6">
<div id="fig-termopares" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-termopares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_3.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-termopares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.2: Rangos de temperatura utilizados para la calibración de los termopares.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="temperatura-radiante" class="level4">
<h4 class="anchored" data-anchor-id="temperatura-radiante">Temperatura radiante</h4>
<p>Para la medición de la temperatura radiante se empleó el QUESTemp 36 (<a href="#fig-quest" class="quarto-xref">Figura&nbsp;<span>4.3</span></a>), un confortímetro diseñado para evaluar el estrés térmico en el ambiente, ya que permite medir la temperatura radiante, la temperatura del aire y la humedad relativa.</p>
<div id="fig-quest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-quest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\images/quest.jpeg" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-quest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.3: Quest Technologies QUESTemp 36.
</figcaption>
</figure>
</div>
<p>El experimento consistió en ubicar el QUESTemp 36 dentro de una caja diseñada para limitar la incidencia directa de la radiación solar, lo que minimizó la influencia de la radiación externa y redujo el efecto de la convección forzada del viento, permitiendo así que la medición se centrara en la radiación térmica del entorno inmediato. Paralelamente, se colocó el sensor TPF1 en condiciones similares para garantizar que ambos dispositivos registraran la temperatura con la menor perturbación posible. Se tomaron datos cada minuto durante 23 horas. Los datos obtenidos se pueden observar en la <a href="#fig-radiante" class="quarto-xref">Figura&nbsp;<span>4.4</span></a>.</p>
<div id="cell-fig-radiante" class="cell" data-execution_count="7">
<div id="fig-radiante" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-radiante-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_4.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-radiante-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.4: Intervalo de medición del QUESTemp 36 y el TPF1 para su calibración.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="velocidad-del-viento" class="level4">
<h4 class="anchored" data-anchor-id="velocidad-del-viento">Velocidad del viento</h4>
<p>El WindMaster de Gill Instruments (<a href="#fig-wind" class="quarto-xref">Figura&nbsp;<span>4.5</span></a>) es un anemómetro ultrasónico de alta precisión diseñado para medir la velocidad y dirección del viento en tres direcciones (u, v, w). En esta campaña se utilizó como instrumento de referencia para la calibración del Wind Sensor.</p>
<div id="fig-wind" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wind-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\images/windmaster.jpg" class="img-fluid figure-img" style="width:35.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wind-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.5: Gill Instruments WindMaster.
</figcaption>
</figure>
</div>
<p>La campaña de calibración tuvo una duración de 1 hora, durante la cual se capturaron datos a una frecuencia de 1 muestra por segundo. Aprovechando las dimensiones del WindSensor (2230 x 680 mm), se posicionó estratégicamente en la parte superior central del WindMaster, previa verificación de que su presencia no interfiriera con las mediciones del anemómetro. En un entorno abierto, el WindSensor registró datos de voltaje, los cuales se utilizaron junto con los datos de velocidad del viento obtenidos del WindMaster para desarrollar una ecuación de calibración que permitiera convertir el voltaje medido a m/s. Los resultados de la campaña se pueden visualizar en la <a href="#fig-viento" class="quarto-xref">Figura&nbsp;<span>4.6</span></a>.</p>
<div id="cell-fig-viento" class="cell" data-execution_count="8">
<div id="fig-viento" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_5.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.6: Comparación de la velocidad del viento registrada por el WindMaster y el voltaje del Wind Sensor para su calibración.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="humedad-relativa-y-co2" class="level4">
<h4 class="anchored" data-anchor-id="humedad-relativa-y-co2">Humedad relativa y CO<sub>2</sub></h4>
<p>Para la campaña de referenciación del SCD30, el instrumento utilizado fue el Fluke 975 AirMeter (<a href="#fig-fluke" class="quarto-xref">Figura&nbsp;<span>4.7</span></a>), este es un instrumento portátil de diagnóstico de la calidad del aire interior. Este dispositivo mide simultáneamente temperatura, humedad relativa, dióxido de carbono (CO<sub>2</sub>) y monóxido de carbono (CO).</p>
<div id="fig-fluke" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fluke-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\images/fluke.png" class="img-fluid figure-img" style="width:15.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fluke-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.7: Fluke 975 AirMeter.
</figcaption>
</figure>
</div>
<p>La campaña consistió en realizar mediciones simultáneas del Fluke 975 AirMeter y del SCD30 durante un período total de 7 horas y 45 minutos, registrando una muestra cada minuto. Para minimizar posibles interferencias, ambos dispositivos se ubicaron lo más próximos posible y se instalaron en una zona aislada de un espacio cerrado, de modo que la presencia humana no afectara los resultados. Los datos obtenidos se muestran en la <a href="#fig-calidad" class="quarto-xref">Figura&nbsp;<span>4.8</span></a>.</p>
<div id="cell-fig-calidad" class="cell" data-execution_count="9">
<div id="fig-calidad" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-calidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_6.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-calidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.8: Comparación de las mediciones del Fluke y el SCD30 durante su campaña de referenciación.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="sonido" class="level4">
<h4 class="anchored" data-anchor-id="sonido">Sonido</h4>
<div id="fig-tes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\images/tes.jpg" class="img-fluid figure-img" style="width:20.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.9: TES-1356 Sound Level Calibrator.
</figcaption>
</figure>
</div>
</section>
<section id="iluminancia" class="level4">
<h4 class="anchored" data-anchor-id="iluminancia">Iluminancia</h4>
<div id="fig-ilum" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ilum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\images/ilum.jpg" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ilum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.10: Mapa de iluminancia generado con una cámara 5MP OV5647 y el software Radiance.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-analisis" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-analisis"><span class="header-section-number">4.3</span> Análisis e interpretación de resultados</h2>
<section id="temperatura-ambiente-1" class="level4">
<h4 class="anchored" data-anchor-id="temperatura-ambiente-1">Temperatura ambiente</h4>
<p>Para la calibración de los termopares, se utilizó Python junto con la librería <code>scikit-learn</code>, una herramienta utilizada para el análisis y modelado de datos. En particular, se aplicó un ajuste por regresión lineal a los datos obtenidos durante la campaña, utilizando los siguientes rangos de tiempo y sus respectivas temperaturas de referencia (<a href="#tbl-temperaturas" class="quarto-xref">Tabla&nbsp;<span>4.2</span></a>).</p>
<div id="tbl-temperaturas" class="hover sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-temperaturas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.2: Temperaturas de referencia y rangos de tiempo.
</figcaption>
<div aria-describedby="tbl-temperaturas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-hover table-sm small caption-top table">
<thead>
<tr class="header">
<th>Temperatura (°C)</th>
<th>Inicio</th>
<th>Final</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10</td>
<td>15:44:01</td>
<td>15:52:31</td>
</tr>
<tr class="even">
<td>20</td>
<td>16:02:06</td>
<td>16:11:52</td>
</tr>
<tr class="odd">
<td>30</td>
<td>16:20:44</td>
<td>16:28:58</td>
</tr>
<tr class="even">
<td>40</td>
<td>16:39:23</td>
<td>16:49:57</td>
</tr>
<tr class="odd">
<td>50</td>
<td>16:58:24</td>
<td>17:08:25</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El ajuste por regresión lineal es una técnica estadística utilizada para modelar la relación entre una variable dependiente y una o más variables independientes. En este caso, la variable dependiente es la temperatura de referencia (<span class="math inline">\(T_{ref}\)</span>), mientras que las variables independientes corresponden a las lecturas obtenidas por cada termopar. El modelo lineal (<a href="#eq-lineal" class="quarto-xref">Ecuación&nbsp;<span>4.1</span></a>) se expresa de la forma:</p>
<p><span id="eq-lineal"><span class="math display">\[
T_{ref} = m \cdot T_{sensor} + b
\tag{4.1}\]</span></span></p>
<p>donde <span class="math inline">\(m\)</span> es la pendiente y <span class="math inline">\(b\)</span> es la ordenada al origen. La regresión lineal permite minimizar el error entre las mediciones del sensor y los valores de referencia, obteniendo ecuaciones de calibración (<a href="#eq-cal-termopares" class="quarto-xref">Ecuación&nbsp;<span>4.2</span></a>) que corrigen las lecturas de cada termopar.</p>
<p><span id="eq-cal-termopares"><span class="math display">\[
\begin{align}
T_{ref} &amp;= 1.0450 \cdot TEMP1 - 2.4327 \\
T_{ref} &amp;= 1.0602 \cdot TEMP2 - 2.8632 \\
T_{ref} &amp;= 1.0814 \cdot TEMP3 - 4.4316 \\
T_{ref} &amp;= 1.0554 \cdot TEMP4 - 3.9348
\end{align}
\tag{4.2}\]</span></span></p>
<p>Al aplicar estas ecuaciones a los datos obtenidos en la campaña, se obtienen los valores corregidos de temperatura para cada termopar. Los resultados de la calibración pueden observarse en la <a href="#fig-ctermopares" class="quarto-xref">Figura&nbsp;<span>4.11</span></a>.</p>
<div id="cell-fig-ctermopares" class="cell" data-execution_count="10">
<div id="fig-ctermopares" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ctermopares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_7.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ctermopares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.11: Resultados de las mediciones de temperatura después de aplicar la ecuación de calibración.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="temperatura-radiante-1" class="level4">
<h4 class="anchored" data-anchor-id="temperatura-radiante-1">Temperatura radiante</h4>
<p>Para la calibración del TPF1/E-20, se aplicó un ajuste por regresión lineal utilizando la librería <code>scikit-learn</code> de Python, a partir de los datos de temperatura registrados simultáneamente por el QUESTemp 36 y el sensor TPF1/E-20. Empleando el mismo modelo lineal descrito en la <a href="#eq-lineal" class="quarto-xref">Ecuación&nbsp;<span>4.1</span></a>, se derivó la siguiente ecuación de calibración (<a href="#eq-cal-radiante" class="quarto-xref">Ecuación&nbsp;<span>4.3</span></a>):</p>
<p><span id="eq-cal-radiante"><span class="math display">\[
T_{ref} = 1.0582 \cdot temp - 1.5553
\tag{4.3}\]</span></span></p>
<p>Al aplicar esta ecuación a los datos obtenidos durante la campaña, se calcularon los valores corregidos para el TPF1/E-20. Los resultados de esta calibración se pueden observar en la <a href="#fig-cradiante" class="quarto-xref">Figura&nbsp;<span>4.12</span></a>.</p>
<div id="cell-fig-cradiante" class="cell" data-execution_count="11">
<div id="fig-cradiante" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cradiante-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_8.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cradiante-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.12: Comparación de las mediciones del QUESTemp 36, el TPF1/E-20 y sus datos tras la calibración.
</figcaption>
</figure>
</div>
</div>
<p>En la tabla <a href="#tbl-error-rad" class="quarto-xref">Tabla&nbsp;<span>4.3</span></a> se observa que, antes de calibrar, el sensor TPF1/E-20 presentaba un error medio de -0.1124, lo que indica un sesgo sistemático que tendía a subestimar la temperatura en comparación con el QUESTemp 36. Tras la aplicación de la ecuación de calibración, el error medio se reduce drásticamente a 4.8948e-15, un valor prácticamente nulo que evidencia la eliminación casi total del sesgo sistemático. Paralelamente, el error medio absoluto disminuye de 0.1518 a 0.0344, lo que implica una mejora significativa en la precisión global de las mediciones. Estos resultados confirman que el proceso de calibración ha corregido eficazmente tanto el sesgo como la dispersión de los datos, permitiendo obtener mediciones de temperatura de alta fiabilidad y precisión, estrechamente alineadas con los valores de referencia del QUESTemp 36.</p>
<div id="tbl-error-rad" class="hover sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-error-rad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.3: Error medio y error medio absoluto antes y después de la calibración.
</figcaption>
<div aria-describedby="tbl-error-rad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-hover table-sm small caption-top table">
<thead>
<tr class="header">
<th>Fase</th>
<th>Error medio</th>
<th>Error medio absoluto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Antes de calibrar</td>
<td>-0.1124</td>
<td>0.1518</td>
</tr>
<tr class="even">
<td>Después de calibrar</td>
<td>4.8948e-15</td>
<td>0.0344</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="velocidad-del-viento-1" class="level4">
<h4 class="anchored" data-anchor-id="velocidad-del-viento-1">Velocidad del viento</h4>
<p>Durante la calibración del Wind Sensor se siguió la metodología proporcionada por el fabricante <span class="citation" data-cites="windsensor">Device (<a href="references.html#ref-windsensor" role="doc-biblioref">2017</a>)</span> en su blog oficial. Según esta fuente, la relación entre la velocidad del viento (WS), el voltaje corregido y la temperatura sigue una ley de potencia descrita por la siguiente ecuación (<a href="#eq-potencia" class="quarto-xref">Ecuación&nbsp;<span>4.4</span></a>):</p>
<p><span id="eq-potencia"><span class="math display">\[
WS = a \cdot \text{voltaje}^b \cdot \text{temp}^c
\tag{4.4}\]</span></span></p>
<p>Adicionalmente, se identificó un error sistemático en las lecturas de voltaje: en condiciones de viento nulo (0 m/s), el Wind Sensor registraba un desfase de 1.1621 V. Este error se corrigió restando 1.1621 V a cada medición, de modo que el voltaje empleado en el análisis reflejara únicamente la contribución del viento.</p>
<p>Para facilitar el ajuste mediante técnicas de regresión, se aplicó una transformación logarítmica a ambos lados de la ecuación, lo que permitió convertir el modelo en una forma lineal (<a href="#eq-potencia-ln" class="quarto-xref">Ecuación&nbsp;<span>4.5</span></a>):</p>
<p><span id="eq-potencia-ln"><span class="math display">\[
\ln(WS) = \ln(a) + b \cdot \ln(\text{voltaje}) + c \cdot \ln(\text{temp})
\tag{4.5}\]</span></span></p>
<p>Esta transformación es crucial, ya que permite emplear técnicas de regresión lineal para estimar los parámetros <span class="math inline">\(ln(a)\)</span>, <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span> a partir de los datos experimentales. Una vez obtenidos, se recupera el parámetro <span class="math inline">\(a\)</span> mediante la función exponencial <span class="math inline">\((a = exp(ln(a)))\)</span> y se formula la ecuación de calibración en su forma original. En este dominio lineal, se utilizó la librería <code>scikit-learn</code> de Python para estimar los parámetros del modelo.</p>
<p>Adicionalmente, se identificó un error sistemático en las lecturas de voltaje: en condiciones de viento nulo (0 m/s), el Wind Sensor registraba un desfase de 1.1621 V. Este error se corrigió restando 1.1621 V a cada medición, de modo que el voltaje empleado en el análisis reflejara únicamente la contribución del viento.</p>
<p>Para el caso elegido, correspondiente a un remuestreo de 10 segundos, el proceso de regresión lineal en el dominio logarítmico produjo la siguiente ecuación de calibración (<a href="#eq-cal-viento" class="quarto-xref">Ecuación&nbsp;<span>4.6</span></a>):</p>
<p><span id="eq-cal-viento"><span class="math display">\[
WS = 26.3431 \cdot \text{voltage}^{1.4273} \cdot \text{temp}^{-0.7631}
\tag{4.6}\]</span></span></p>
<p>Esta ecuación se emplea para convertir las mediciones de voltaje (tras aplicar la corrección) y de temperatura en valores precisos de velocidad del viento (m/s).</p>
<p>El coeficiente de correlación obtenido tras aplicar el modelo es un indicador de la calidad del ajuste. Valores de correlación cercanos a 1 implican una excelente concordancia entre las mediciones del Wind Sensor (tras la calibración) y las obtenidas con el WindMaster, lo que confirma que el modelo captura de manera adecuada la variabilidad de los datos. En la <a href="#tbl-corr-viento" class="quarto-xref">Tabla&nbsp;<span>4.4</span></a> se resumen los coeficientes de correlación para los diferentes intervalos de remuestreo.</p>
<div id="tbl-corr-viento" class="hover sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-corr-viento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.4: Coeficientes de correlación para los distinto remuestreos.
</figcaption>
<div aria-describedby="tbl-corr-viento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-hover table-sm small caption-top table">
<thead>
<tr class="header">
<th>Remuestreo</th>
<th>Coeficiente de correlación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3 segundos</td>
<td>0.7622</td>
</tr>
<tr class="even">
<td>5 segundos</td>
<td>0.8079</td>
</tr>
<tr class="odd">
<td>10 segundos</td>
<td>0.8637</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El aumento progresivo en el coeficiente de correlación, alcanzando 0.8637 para un remuestreo de 10 segundos, indica que el modelo de calibración y la corrección del desfase mejoran significativamente la consistencia de las mediciones del Wind Sensor con respecto al WindMaster. Estos hallazgos validan la eficacia del procedimiento de calibración y pueden observarse en la <a href="#fig-cviento" class="quarto-xref">Figura&nbsp;<span>4.13</span></a>.</p>
<div id="cell-fig-cviento" class="cell" data-execution_count="12">
<div id="fig-cviento" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cviento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_9.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cviento-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.13: Comparación de las mediciones de velocidad del viento registradas por el WindMaster y el Wind Sensor tras su calibración.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="humedad-relativa-y-co2-1" class="level4">
<h4 class="anchored" data-anchor-id="humedad-relativa-y-co2-1">Humedad relativa y CO<sub>2</sub></h4>
<p>Para esta campaña de referenciación, se compararon directamente los datos de medición obtenidos por el SCD30 y el Fluke 975 AirMeter, dado que el SCD30 se calibra de forma independiente. Se realizó el cálculo de errores, en particular el error medio y el error medio absoluto, para evaluar la discrepancia entre las mediciones de ambos instrumentos. Estos errores permiten determinar si existe algún sesgo sistemático en las lecturas del SCD30 respecto al Fluke.</p>
<p>El error medio se obtiene al calcular la diferencia promedio entre las mediciones del SCD30 y las del Fluke. Un valor negativo indica que, en promedio, el SCD30 tiende a subestimar la variable, mientras que un valor positivo indica una sobreestimación. El error medio absoluto cuantifica la magnitud promedio del error sin considerar el signo, ofreciendo una medida de la precisión global de las mediciones.</p>
<p>La <a href="#tbl-error-calidad" class="quarto-xref">Tabla&nbsp;<span>4.5</span></a> resume los resultados obtenidos para cada variable:</p>
<div id="tbl-error-calidad" class="hover sm quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-error-calidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.5: Error medio y error medio absoluto para cada variable del SCD30 con respecto al Fluke.
</figcaption>
<div aria-describedby="tbl-error-calidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-hover table-sm small caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Error medio</th>
<th>Error medio absoluto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Humedad relativa</td>
<td>-2.1681</td>
<td>2.1681</td>
</tr>
<tr class="even">
<td>CO<sub>2</sub></td>
<td>9.6543</td>
<td>13.1565</td>
</tr>
<tr class="odd">
<td>Temperatura</td>
<td>0.8853</td>
<td>0.8853</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La tabla indica que, para la humedad relativa, el SCD30 subestima en promedio 2.1681 unidades respecto al Fluke, mientras que para la concentración de CO<sub>2</sub> se observa una sobreestimación de 9.6543 unidades en promedio, con un error medio absoluto mayor que su error medio, lo que sugiere una mayor dispersión en las mediciones. En el caso de la temperatura, la discrepancia es menor, con un error medio de 0.8853.</p>
<p>La correlación entre las mediciones de ambos instrumentos se visualiza en la <a href="#fig-ccalidad" class="quarto-xref">Figura&nbsp;<span>4.14</span></a>, lo que respalda la evaluación de precisión y consistencia. Un coeficiente de correlación elevado indicaría que, a pesar de los errores sistemáticos, la tendencia de las mediciones del SCD30 sigue de cerca la del Fluke.</p>
<div id="cell-fig-ccalidad" class="cell" data-execution_count="13">
<div id="fig-ccalidad" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ccalidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe scrolling="no" width="100%" height="545px" src="iframe_figures/figure_10.html" frameborder="0" allowfullscreen=""></iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ccalidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.14: Correlación de las mediciones de humedad relativa, CO<sub>2</sub> y temperatura entre el Fluke y el SCD30.
</figcaption>
</figure>
</div>
</div>
</section>
<section id="sonido-1" class="level4">
<h4 class="anchored" data-anchor-id="sonido-1">Sonido</h4>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-windsensor" class="csl-entry" role="listitem">
Device, Modern. 2017. <span>«Calibrating The Rev. P Wind Sensor From A New Regression»</span>. <a href="https://moderndevice.com/blogs/documentation/calibrating-the-rev-p-wind-sensor-from-a-new-regression">https://moderndevice.com/blogs/documentation/calibrating-the-rev-p-wind-sensor-from-a-new-regression</a>.
</div>
<div id="ref-thingsboard" class="csl-entry" role="listitem">
ThingsBoard. 2023. <span>«ThingsBoard: Open-source IoT platform for data collection, processing, visualization, and device management»</span>. <a href="https://thingsboard.io/">https://thingsboard.io/</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter_3.html" class="pagination-link" aria-label="Diseño y construcción del DTHIS-C">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Diseño y construcción del DTHIS-C</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter_5.html" class="pagination-link" aria-label="Conclusiones">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusiones</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>